for pull request
tofi86/universalJavaApplicationStub pull request #105
Opened 2021-02-09 17:06 UTC by RBornat

**Please check if the PullRequest fulfills these requirements:**

(Add x between brackets to check.)

- [ ] I’ve updated my fork from the `develop` branch before proposing this pull request
- [ ] I’m making this pull request against the `develop` branch
- [ ] I’ve tested the changes for bug fixes and/or features
- [ ] I’ve documented new code

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, other)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (What changes might users need to make in their application / PList file due to this PR?)

**Other information:**

2021-04-15 18:02 UTC, tofi86 requested changes

2021-04-15 18:04 UTC, tofi86 commented
> The version search information didn't seem to work in Big Sur (but /usr/libexec/java_home does).

Also note: Version 3.1.0 (January 7) fixed macOS Big Sur support: https://github.com/tofi86/universalJavaApplicationStub/releases

So maybe you want to try the latest version 3.2.0 and see whether it works better for you :-)

2021-04-17 06:29 UTC, RBornat commented on src/universalJavaApplicationStub
> +	APP_PACKAGE="${AppPackageFolder}"
Fine.

2021-04-17 06:32 UTC, RBornat commented on src/universalJavaApplicationStub
> +	JVMfound=`/usr/libexec/java_home 2>&1 -v "${JVMVersion}"`
I sent you a separate message (I think) which explains why I did this. I apologise, sincerely, for doing this the way that I did: it was just from ignorance. The fix, though violent, worked for me.

2021-04-17 06:35 UTC, RBornat commented
At present I'm exploring using jmod and jlink, so that I can distribute an application that isn't subject to the vagaries of java distributions and user reluctance to upgrade. If I can't get that to work I shall certainly return and try the new versions of your software. 

I apologise again for what must have seemed a very rude pull request: it was due to my ignorance and inexperience of github, honestly. I'm very grateful for your software, which worked well for me for ages.

2021-04-17 06:35 UTC, closed without merging